'use strict';
const LEVELS=['Préscolaire','1re année','2e année','3e année','4e année','5e année','6e année'];
const SKILLS=['Compter les objets','Additionner et soustraire','Calculer avec les dizaines','Multiplier et diviser','Explorer les fractions','Calculer avec les décimales','Fractions et pourcentages'];
const DIFFICULTIES=['Douce','Habituelle','Défi'];
const ANIMALS=[['🐶','un petit chien'],['🐱','un chat curieux'],['🐰','un lapin gourmand'],['🐢','une tortue patiente'],['🐹','un petit hamster'],['🐦','un oiseau joyeux'],['🐶','un chien joueur'],['🐱','un chat câlin']];
const rand=(min,max)=>Math.floor(Math.random()*(max-min+1))+min;
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=rand(0,i);[b[i],b[j]]=[b[j],b[i]];}return b;};
const fmt=n=>Number(n.toFixed(4)).toLocaleString('fr-CA',{maximumFractionDigits:4});
function makeQuestion(grade,difficulty){
 let text,answer,explanation,count=0,options;
 const numeric=(value,step=1)=>{answer=fmt(value);const set=new Set([answer]);for(let tries=0;set.size<4&&tries<100;tries++){const other=value+rand(-5,5)*step;if(other>=0)set.add(fmt(other));}let i=1;while(set.size<4)set.add(fmt(value+i++*step));options=shuffle([...set]);};
 if(grade===0){count=rand(1,[5,8,12][difficulty]);text='Combien de chiens vois-tu ?';numeric(count);explanation=`Compte chaque chien une seule fois. Il y en a ${count}.`;}
 else if(grade===1){const cap=[5,10,20][difficulty],a=rand(1,cap),b=rand(1,cap);if(difficulty>0&&rand(0,1)){const x=Math.max(a,b),y=Math.min(a,b);text=`${x} − ${y} = ?`;numeric(x-y);explanation=`Pars de ${x} et recule de ${y}. Tu arrives à ${x-y}.`;}else{text=`${a} + ${b} = ?`;numeric(a+b);explanation=`${a} et encore ${b}, cela fait ${a+b}.`;}}
 else if(grade===2){const cap=[20,50,99][difficulty],a=rand(10,cap),b=rand(1,cap);if(rand(0,1)){const x=Math.max(a,b),y=Math.min(a,b);text=`${x} − ${y} = ?`;numeric(x-y);explanation=`${x} moins ${y} donne ${x-y}. Sépare les dizaines et les unités si cela t’aide.`;}else{text=`${a} + ${b} = ?`;numeric(a+b);explanation=`En additionnant les dizaines puis les unités, ${a} + ${b} = ${a+b}.`;}}
 else if(grade===3){const a=difficulty===0?[2,5,10][rand(0,2)]:rand(2,difficulty===1?10:12),b=rand(2,difficulty===0?5:10);if(difficulty>0&&rand(0,1)){text=`${a*b} ÷ ${a} = ?`;numeric(b);explanation=`${a} × ${b} = ${a*b}, donc ${a*b} ÷ ${a} = ${b}.`;}else{text=`${a} × ${b} = ?`;numeric(a*b);explanation=`${a} groupes de ${b} donnent ${a*b}.`;}}
 else if(grade===4){const d=[2,3,4,5,6,8][rand(0,difficulty===0?2:5)],n=rand(1,d-1),m=rand(2,difficulty===2?5:3);if(difficulty===2&&rand(0,1)){const k=rand(1,d-1);text=`${n}/${d} + ${k}/${d} = ?`;answer=`${n+k}/${d}`;options=shuffle([answer,`${n+k}/${d*2}`,`${n+k+1}/${d}`,`${Math.max(0,n+k-1)}/${d}`]);explanation=`Les dénominateurs sont identiques : on additionne ${n} et ${k}, et on garde ${d}. La réponse est ${answer}.`;}else{text=`${n}/${d} = ?`;answer=`${n*m}/${d*m}`;options=shuffle([answer,`${n*m+1}/${d*m}`,`${n}/${d*m}`,`${n*m}/${d*m+1}`]);explanation=`Multiplie le haut et le bas par ${m} : ${n}/${d} = ${answer}.`;}}
 else if(grade===5){const unit=difficulty===0?10:100,a=rand(1,difficulty===2?999:99),b=rand(1,difficulty===2?999:99);if(difficulty===2&&rand(0,1)){text=`${fmt(a/unit)} × 10 = ?`;numeric(a/unit*10,.1);explanation=`Multiplier par 10 donne ${fmt(a/unit*10)} : chaque chiffre prend une valeur dix fois plus grande.`;}else{text=`${fmt(a/unit)} + ${fmt(b/unit)} = ?`;numeric((a+b)/unit,1/unit);explanation=`Aligne les virgules pour additionner : ${fmt(a/unit)} + ${fmt(b/unit)} = ${fmt((a+b)/unit)}.`;}}
 else {if(difficulty===0){const d=[2,4,5,10][rand(0,3)],n=rand(1,d-1);text=`${n}/${d} de 100 = ?`;numeric(100*n/d,5);explanation=`Divise 100 par ${d}, puis multiplie par ${n} : tu obtiens ${fmt(100*n/d)}.`;}else if(difficulty===1||rand(0,1)){const p=[10,20,25,50,75][rand(0,4)],n=rand(2,12)*20;text=`${p} % de ${n} = ?`;numeric(p*n/100,5);explanation=`${p} % veut dire ${p} sur 100 : ${n} × ${p} ÷ 100 = ${fmt(p*n/100)}.`;}else{const a=rand(2,12),b=rand(2,12),c=rand(2,20);text=`${c} + ${a} × ${b} = ?`;numeric(c+a*b);explanation=`La multiplication passe en premier : ${a} × ${b} = ${a*b}, puis ${c} + ${a*b} = ${c+a*b}.`;}}
 return {text,answer,options,explanation,count};
}
if(typeof module!=='undefined')module.exports={makeQuestion,LEVELS,DIFFICULTIES};
if(typeof document!=='undefined'){
 const content=document.querySelector('#game-content');let grade=0,difficulty=1,state='start',questions=[],index=0,stars=0,attempts=0,solved=false;const wrong=new Set();
 document.querySelector('.grade-grid').innerHTML=LEVELS.map((label,i)=>`<label class="choice"><input type="radio" name="grade" value="${i}" ${i===0?'checked':''}><span>${label}</span></label>`).join('');
 document.querySelector('.difficulty-list').innerHTML=DIFFICULTIES.map((label,i)=>`<label class="choice"><input type="radio" name="difficulty" value="${i}" ${i===1?'checked':''}><span>${label}</span></label>`).join('');
 document.querySelector('#grades').addEventListener('change',e=>{grade=Number(e.target.value);renderIntro();});
 document.querySelector('#difficulties').addEventListener('change',e=>{difficulty=Number(e.target.value);renderIntro();});
 const stopVoice=()=>{if('speechSynthesis'in window)window.speechSynthesis.cancel();};
 function configure(enabled){document.querySelectorAll('.settings input').forEach(el=>el.disabled=!enabled);document.querySelector('#change-settings').hidden=enabled;}
 function renderIntro(){state='start';configure(true);stopVoice();content.innerHTML=`<div class="intro"><div class="animal-line" aria-hidden="true"><span>🐶</span><span>🐱</span><span>🐰</span></div><h3>Les animaux t’attendent !</h3><p>Aide Mattéo à préparer les soins de ses 8 petits patients. Pour chacun, résous une énigme de nombres.</p><div class="preview-skill">${LEVELS[grade]} · ${SKILLS[grade]}</div><button class="primary" id="start">Ouvrir la clinique</button><p class="gentle">8 énigmes · ${DIFFICULTIES[difficulty]} · à ton rythme</p></div>`;document.querySelector('#start').onclick=startGame;}
 function startGame(){state='play';index=0;stars=0;questions=[];const seen=new Set();let tries=0;while(questions.length<8){const q=makeQuestion(grade,difficulty),key=q.text+q.count;if(!seen.has(key)||tries++>100){seen.add(key);questions.push(q);}}configure(false);renderQuestion();}
 function renderQuestion(){stopVoice();attempts=0;solved=false;wrong.clear();const q=questions[index],animal=ANIMALS[index];content.innerHTML=`<div class="round"><div class="round-top"><span class="round-label">${LEVELS[grade]} · Patient ${index+1} sur 8</span><span class="stars">⭐ ${stars} étoile${stars>1?'s':''}</span></div><div class="progress" role="progressbar" aria-label="Patients aidés" aria-valuemin="0" aria-valuemax="8" aria-valuenow="${index}"><span style="width:${index/8*100}%"></span></div><div class="patient"><span class="animal" aria-hidden="true">${animal[0]}</span>Tu aides ${animal[1]}</div><h3 class="question" id="question-title">${q.text}</h3>${q.count?`<div class="counts" role="img" aria-label="${q.count} chiens à compter">${Array.from({length:q.count},()=>'<span class="count-item" aria-hidden="true">🐶</span>').join('')}</div>`:''}<button class="read-button" id="read">🔊 Écouter la consigne</button><div class="answers" role="group" aria-labelledby="question-title">${q.options.map((o,i)=>`<button class="answer" data-answer="${i}" aria-label="Réponse ${o}">${o}</button>`).join('')}</div><p class="feedback" id="feedback" role="status">Choisis la bonne réponse. Tu peux essayer plusieurs fois.</p><div class="round-actions"><button class="text-button" id="hint">Un petit indice</button><button class="primary" id="next" hidden>${index===7?'Voir mon résultat':'Patient suivant'}</button></div></div>`;
 content.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answerQuestion(Number(b.dataset.answer)));
 document.querySelector('#hint').onclick=()=>{document.querySelector('#feedback').textContent=q.explanation;};
 document.querySelector('#next').onclick=()=>{index++;if(index===8)renderResult();else renderQuestion();};
 document.querySelector('#read').onclick=()=>readQuestion(q);
 }
 function answerQuestion(optionIndex){if(state!=='play'||solved||wrong.has(optionIndex))return {accepted:false};const q=questions[index],button=content.querySelector(`[data-answer="${optionIndex}"]`),feedback=document.querySelector('#feedback');attempts++;if(q.options[optionIndex]===q.answer){solved=true;if(attempts===1)stars++;button.classList.add('correct');content.querySelectorAll('[data-answer]').forEach(b=>b.disabled=true);feedback.classList.add('success');feedback.textContent=`Bien joué ! ${q.explanation}`;content.querySelector('.stars').textContent=`⭐ ${stars} étoile${stars>1?'s':''}`;document.querySelector('#next').hidden=false;document.querySelector('#hint').hidden=true;content.querySelector('[role="progressbar"]').setAttribute('aria-valuenow',index+1);content.querySelector('.progress span').style.width=`${(index+1)/8*100}%`;}else{wrong.add(optionIndex);button.disabled=true;button.classList.add('wrong');feedback.textContent=attempts===1?'Presque ! Prends ton temps et essaie une autre réponse.':`Voici un coup de main : ${q.explanation}`;}return {accepted:true,correct:solved,stars};}
 function readQuestion(q){const feedback=document.querySelector('#feedback');if(!('speechSynthesis'in window)){feedback.textContent='La lecture vocale n’est pas disponible dans ce navigateur. Tu peux lire la consigne à l’écran.';return;}stopVoice();const spoken=q.count?'Compte les chiens à l’écran. Combien y en a-t-il ?':q.text.replace(/−/g,' moins ').replace(/\+/g,' plus ').replace(/×/g,' multiplié par ').replace(/÷/g,' divisé par ').replace(/=/g,' égale ').replace(/%/g,' pour cent ').replace(/\//g,' sur ').replace(/\?/g,'');const utterance=new SpeechSynthesisUtterance(spoken);utterance.lang='fr-CA';utterance.rate=.85;const voice=window.speechSynthesis.getVoices().find(v=>v.lang==='fr-CA')||window.speechSynthesis.getVoices().find(v=>v.lang.startsWith('fr'));if(voice)utterance.voice=voice;utterance.onerror=()=>{if(state==='play')document.querySelector('#feedback').textContent='La lecture vocale n’a pas pu démarrer. Tu peux lire la consigne à l’écran.';};window.speechSynthesis.speak(utterance);}
 function renderResult(){state='result';stopVoice();content.innerHTML=`<div class="result"><div class="medal" aria-hidden="true">🏅</div><h3>Une belle journée à la clinique !</h3><p>Tu as aidé les 8 animaux de Mattéo. Bravo d’avoir pris le temps de trouver chaque réponse !</p><div class="result-score">⭐ ${stars} étoile${stars>1?'s':''} sur 8</div><p>Une étoile pour chaque réponse trouvée du premier coup. Chaque essai t’aide à apprendre.</p><div class="result-actions"><button class="primary" id="replay">Une nouvelle partie</button><button class="text-button" id="home">Choisir un autre niveau</button></div></div>`;document.querySelector('#replay').onclick=startGame;document.querySelector('#home').onclick=renderIntro;document.querySelector('#replay').focus();}
 document.querySelector('#change-settings').onclick=renderIntro;
 renderIntro();
 window.addEventListener('pagehide',stopVoice,{once:true});
}
